# Maintain a consistent coding style throughout the entire project codebase to
# ensure readability and maintainability.  Consistent style not only improves
# collaboration but also makes the code easier to review and debug.
#
# Configuration file for Alacritty terminal emulator.  Alacritty is a modern
# terminal emulator that comes with sensible defaults, but allows for extensive
# config.  For more information about, refer to the official documentation at:
#
#       https://alacritty.org/
#
# The rules are still a work in progress and subject to change.  I still need
# to think about this configuration file, and for now this is a base template.

[window]
dimensions = { columns = 144, lines = 43 }
opacity = 1.0
decorations = "Full"
decorations_theme_variant = "Dark"

[scrolling]
history = 100000
multiplier = 4

[colors.primary]
foreground = "#D8D8D8"
background = "#17191E"

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 512
blink_timeout = 16

[font]
normal.family = "Departure Mono Nerd Font Mono"
size = 8.0
#normal.family = "Terminess Nerd Font Propo"
#size = 11.0
